version: "3"
services:
  todo:
    build: .
    volumes:
      - ../.:/code
    # command: python /code/app/app.py
    ports:
      - "8082:8082"
    links:
      - todo-db
    depends_on:
      - todo-db
  todo-db:
    image: mysql:5.7.20
    volumes:
      - ./init.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    ports:
      - 3307:3307
    environment:
      MYSQL_ROOT_PASSWORD: p@ssw0rd123
      MYSQL_DATABASE: todoapp
# networks:
#   todo-api:
#     driver: "bridge"
